[package]
name = "chors"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
indexmap = "2.2.6"
ratatui = "0.26.3"
regex = "1.10.5"
uuid = { version = "1.8.0", features = ["v7"] }
